### ISSUE TITLE
Request : Add Extension to Firefox Store

### ISSUE THREAD

**Issue by tbringuier** [jared-schwalbe/remove-ads-from-photopea#2]
Hi,

Could you please add the app to the firefox store ?

Thanks

**Comment by jared-schwalbe** [comment]
I just published an addon in the firefox store per your request. It should be available after it is reviewed in 12 to 48 hours.

**Comment by jared-schwalbe** [comment]
@MichelBaie https://addons.mozilla.org/en-US/firefox/addon/remove-ads-from-photopea
