### ISSUE TITLE
Full screen 

### ISSUE THREAD

**Issue by Abeelme** [jared-schwalbe/remove-ads-from-photopea#3]
Hello
Problem with full-screen not showing all page 
![Screenshot_20230212_024245_Lemur Browser](https://user-images.githubusercontent.com/44150697/218288597-98d8b1a6-fad2-4496-b15f-d482c2f52cac.jpg)

**Comment by jared-schwalbe** [comment]
@Abeelme This might be fixed now. Feel free to try it out again.
