### ISSUE TITLE
Right margin

### ISSUE THREAD

**Issue by Bubsjz** [jared-schwalbe/remove-ads-from-photopea#4]
Hi, the platform is not displayed on its full width. Is it how it should be? Thank you.

![margin0](https://user-images.githubusercontent.com/131241349/232999357-6bfa8bd7-56e2-4eba-84b0-f229f99ab71f.png)

**Comment by mihail-antonov** [comment]
Yeah, it's not working properly on the downloaded version of PhotoPea.

**Comment by jared-schwalbe** [comment]
@mihail-antonov Only on the downloaded version? Not sure that I’ve tested that. I’ll check it out.

**Comment by mihail-antonov** [comment]
> @mihail-antonov Only on the downloaded version? Not sure that I’ve tested that. I’ll check it out.

On the downloaded version, yeah. The ads are hidden but there is a light gray space in the right which is still shrinking the canvas.

**Comment by Bubsjz** [comment]
The online version seems to have a gray space on the right as well

**Comment by jared-schwalbe** [comment]
@mihail-antonov @Bubsjz what is your screen/window resolution?

**Comment by Bubsjz** [comment]
1920x1080

**Comment by Bubsjz** [comment]
![34521](https://user-images.githubusercontent.com/131241349/236533411-cb8d312e-a4d0-49f1-b063-189166da0d9c.jpg)

**Comment by jared-schwalbe** [comment]
@Bubsjz one more quick favor to get this fixed… can you open the browser console and check the value of `window.screen.width`?

**Comment by Bubsjz** [comment]
sure, could it be 1536?

**Comment by jared-schwalbe** [comment]
Huh, ok interesting. I’ll see if I can figure out a solution soon. Thanks.

**Comment by Bubsjz** [comment]
Thank you!

**Comment by jared-schwalbe** [comment]
Closing now that this is quite stale. If you're still experiencing this issue after v2.0.0 please reach out again.
