### ISSUE TITLE
No Longer Working 

### ISSUE THREAD

**Issue by EVTECH-TECHNOLOGIES** [jared-schwalbe/remove-ads-from-photopea#6]
![Issue](https://github.com/user-attachments/assets/881f35a2-e4fc-42e1-9dec-a026fa3d78ac)

**Comment by MasterKia** [comment]
Use uBlock Origin, it works.

**Comment by jsousou77** [comment]
Can confirm the extension doesn't work anymore but I'm running uBlock Origin and it doesn't work either.

**Comment by MasterKia** [comment]
@Electronik21 Are you using Photopea with an account?

If so, test this filter:
```adb
photopea.com##+js(trusted-rpnt, script, added=false;, "added=false;Object.defineProperty(window, 'innerWidth', {get() { return document.documentElement.offsetWidth + 320 },});")
```

Make sure `Allow custom filters requiring trust` is enabled.

**Comment by jsousou77** [comment]
I'm not using an account, I tried the filter and it didn't do anything.

**Comment by jared-schwalbe** [comment]
I also see that it is no longer working. But it doesn't work with uBlock Origin either (not using an account).

@MasterKia This is sorta your fault. Photopea is constantly resizing elements on the page relative to the screen size. Before you tagged the creator in that issue, he was using `window.innerWidth` which I was able to change the value of so that I could push the ads off the screen. Now he's using `window.screen.width` (or maybe something else) which is not writable so my strategy no longer works.

I'll see if I can maybe come up with another solution.

**Comment by MasterKia** [comment]
@jared-schwalbe This filter has been working in uBO for the past several months:
```
{Object.defineProperty(window, 'innerWidth', {get() { return document.documentElement.offsetWidth + 320 },});}
```

We had been over-scretching the UI for premium users due to an oversight, so the dev responded back by blocking that method.
See:
`https://github.com/brave/brave-browser/issues/41552`

**Comment by jared-schwalbe** [comment]
I just tested that filter in an incognito browser and it does not work.

**Comment by MasterKia** [comment]
It did work until a few days ago.

**Comment by MasterKia** [comment]
> which is not writable

@jared-schwalbe A trick:
```js
const originalScreen = window.screen;

const customScreen = new Proxy(originalScreen, {
    get(target, property) {
        if (property === 'width') {
            return 1024; // Return custom value
        }
        return target[property];
    }
});

Object.defineProperty(window, 'screen', {
    value: customScreen,
    configurable: true
});

console.log(window.screen.width); // Will log: 1024
```

**Comment by jared-schwalbe** [comment]
I don't think he's using `window.screen.width`. Adjusting that value doesn't make it work. I'll continue poking at it to see if I can get something working.

In the future, let's keep our strategy for hiding these ads quiet!

**Comment by jared-schwalbe** [comment]
@EVTECH-TECHNOLOGIES @Electronik21 @MasterKia I have published an update that should restore functionality to the browser extension. Please make sure you have v2.0.0 installed and try again. Thanks!

**Comment by jsousou77** [comment]
It works now, thank you!

**Comment by Fuadevil007** [comment]
thank you

**Comment by MasterKia** [comment]
@jared-schwalbe Just a heads-up:
https://x.com/photopeacom/status/1888310593289085294

Photopea seems to have removed the ad space for now, so your extension now breaks site.
